### PR TITLE
Change before/after example event ordering

### PR DESCRIPTION
**Pull request by andrew-sumner**
Goal is to ensure that extensions get beforeExample events in order extensions registered, and afterExample events in reverse order to which they were registered.  I've encountered cross extension issues with the logging extension as it is de-registering before other extensions have finished logging.

I have a TODO in the code for you to think about as I'm worried about the impact on scoped objects.

I will need to run this against MSD code base to confirm no adverse imacts

### CODE REVIEW

**Comment by nigelcharman** [comment]
@andrew-sumner, you're right, there is an effect. 

For ["before" examples](http://concordion.org/instrumenting/java/html/#before-examples), scoped objects are now being destroyed at the end of the "before" example, and the `@BeforeExample` and `@AfterExample` methods are now being called for the "before" example. 

The ScopedFieldFixture spec is not currently failing since there is no `destroy()` method on the ScopedFields. Adding the following method to the scoped objects makes the spec fail with the new implementation:

```
        @Override
        protected void destroy(AtomicInteger counter) {
            counter.set(-1);
        }
```

What I'd like to see is a separate PR that improves the current specs to bake in functionality, before making this change.

I think we need to check that we have the following dimensions covered for the `@BeforeExample`/`@AfterExample`, ScopedField and ExampleListener specs:

1. normal examples / before examples
2. normal result (either success or failure) / exception 

Can you think of any other dimensions we need to cover?

**Comment by nigelcharman** [comment]
@andrew-sumner I took the liberty of updating the ScopedFieldFixture spec on master to include the above change, and re-ran the Travis build for this PR, causing it to fail. (It's a new Green-Red-Green-Refactor workflow ;)

I'd still like us to review and update the specs to have the coverage I detailed above. Feel free to have a go, or I'll do some more tomorrow.

**Comment by andrew-sumner** [comment]
I've added a couple of methods to the public API to ensure example scoped methods are destroyed at the correct location.  Your comments in the original pull request asked to avoid doing that but I don't see a way around it.

That's probably reached the limits of my knowledge...

**Comment by nigelcharman** [comment]
I've updated some specs on master to lock in more behaviour. This has highlighted a couple of potential issues:

1) @BeforeExample and @AfterExample methods are now being called for the 'before' example
2) The order of @BeforeExample and the 'before' example being called is now reversed. Not sure if this is an issue since it wasn't defined before.

Since the changes have introduced conflicts, I've done a merge and created a PR on your repo @andrew-sumner. This currently has failing tests. If you're happy to accept the PR, you can merge it and this PR should be updated.

We'll then need to look at how to modify the code to satisfy all the desired behaviours.

**Pull request merged**
