### PR TITLE
verifyRowsUnordered

### PR DESCRIPTION
**Pull request by gmandnepr**
Hi all,

This pull request contains new command (verifyRowsUnordered).
Command verify all rows from evaluated collection are present in expected table, this time order does not matter. 

Please let me know if You agree with the changes.

### CODE REVIEW

**Comment by nigelcharman** [comment]
Thanks for the PR. And sorry you had a large merge to deal with. It was unfortunate timing that we pulled in Tim Wright's changes for the example command at the same time as you were working on this.

Your changes are good, and the spec is clear.

However, I have a couple of concerns with the implementation:

1. For tables with multiple columns, the current `verifyRows` command will assert on the columns one-by-one, potentially resulting in a partial match where some columns pass their assertion and some fail their assertion. For example, where the fixture returns an object containing the values John | Travolta | 1954, verifyRows will return:

  image

  However, the `verifyRowsUnordered` command matches against the whole row. If the whole row doesn't match, it is marked as failed:

  image

  In this respect, it may be better to term the new command `matchRows` rather than `verifyRowsUnordered`. I'm not sure what the right answer is here - I suggest we ask users to see what they want.

2. If possible, I'd prefer not to add a new `verifyInBackground` method to `AbstractCommand`, since it adds complexity and may require implementations to be added to existing extensions that implement the `verify` method.

Given this, I'm keen that we explore the requirements a bit further and consider alternative implementations. As an example, we could order the actual and expected lists before comparison. 

When used with multiple columns, we may need to define which columns define the identity of the row and which are properties for comparison. As an example, there is some description of how Fitnesse addresses this at http://gojko.net/FitNesse/book/ch09s04.html.

**Comment by gmandnepr** [comment]
Thanks for reviewing,

##1 As for the partial row matching, lets say expected table is
| First name  | Last name | Some year |
| ------------- | ------------- | ------------- |
| John  | Travolta  | 1988 |
| John  | Travolta  | 1989 |
and actual result is 
| First name  | Last name | Some year |
| ------------- | ------------- | ------------- |
| John  | Travolta  | 1990 |
Should I try match it to any of the existing ones? (Like trying to match any first one that has less different columns)

Also I like name `matchRows` more then `verifyRowsUnordered`

## I absolutely agree about this point. 

I would like to avoid specify key in  tables to have simpler spec, if that possible....

Let me propose another PR that will not introduce verifyInBackground, but will use something like BackgroundResultRecorder. I believe this way it will be less code changes (especially in interfaces). Also it will handle partial matches.

**Comment by nigelcharman** [comment]
Hi, I think it will be difficult to determine what the correct result will be for partial matches without specifying keys in the table.

In your example, if the actual result is the following, it will be hard to determine what to match:

| First name  | Last name | Some year |
| ------------- | ------------- | ------------- |
| Jim  | Travolta  | 1988 |
| John  | Smith  | 1989 |
| John  | Travolta  | 1990 |

whereas if the first 2 columns were specified as keys, the first 2 rows would be surplus and we would match the 3rd row against one of the 2 expected rows.

Let's open the discussion up to the Concordion Google Group. Would you update the spec to whatever you think is best, and post to the group for feedback?

**Comment by gmandnepr** [comment]
Sure, I'll write couple of options

**Comment by gmandnepr** [comment]
Posted corresponding topic in concordion-dev on google groups

**Pull request closed without merging**
